### ISSUE TITLE
it does'nt works

### ISSUE THREAD

**Issue by OpenSrcerer** [BytesToBits/LockPass#2]
it dont work

**Comment by Nemika-Haj** [comment]
Hello @OpenSrcerer!

We are deeply sorry about your issues. However, due to unfortunate events, we are not able to give a fuck.

If you experience any future issues, please consider contacting us at support@bytestobits.dev! Even though we'd rather not hear from you again.

Have a splendid afternoon.

**Comment by VulpoTheDev** [comment]
It's borked
